#!/usr/bin/python

CHUNK_SERVER_IP = "192.168.1.12"
CHUNK_SERVER_PORT = 50051

CHUNK_SIZE = 4*1024

ID_INDEX = 0
HASH_INDEX = 1
FILENAME_INDEX = 2
OFFSET_INDEX = 3
LEN_INDEX = 4
INCACHE_INDEX = 5
SSIP_INDEX = 6
SSPORT_INDEX = 7

TMP_DIR = "/tmp/fuse/"
CHUNKS_DIR = "chunks/"
