# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import request_pb2 as request__pb2
import response_pb2 as response__pb2


class ChunkServerStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetResponse = channel.unary_unary(
        '/perfuse.ChunkServer/GetResponse',
        request_serializer=request__pb2.Request.SerializeToString,
        response_deserializer=response__pb2.Response.FromString,
        )


class ChunkServerServicer(object):

  def GetResponse(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChunkServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetResponse': grpc.unary_unary_rpc_method_handler(
          servicer.GetResponse,
          request_deserializer=request__pb2.Request.FromString,
          response_serializer=response__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'perfuse.ChunkServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
