import Utils

CHUNKS_DIR = "chunks/"
DB_NAME = "CHUNKS"

CHUNK_SERVER_IP = "192.168.1.13"
CHUNK_SERVER_PORT = "50051"

STORAGE_SERVER_PORT = "50004"

STORAGE_SERVER_IP = Utils.get_my_ip()

TRIGGER_LEVEL = 0.6

DISK_BALANCER_PERIOD = 5
